repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.14.1
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "."]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-validate
      - id: terraform-fmt
